apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-microservice
  template:
    metadata:
      labels:
        app: flask-microservice
    spec:
      containers:
        - name: flask-microservice
          image: vishnu17o7/cloud-main-service:v1
          ports:
          - containerPort: 5000
