services:
  product-catalog-service:
    build:
      context: ./product_catalog_service
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    networks:
      - ecommerce-network

  order-management-service:
    build:
      context: ./order_management_service
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    networks:
      - ecommerce-network

  payment-service:
    build:
      context: ./payment_service
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    networks:
      - ecommerce-network

  inventory-service:
    build:
      context: ./inventory_service
      dockerfile: Dockerfile
    ports:
      - "5004:5004"
    networks:
      - ecommerce-network

  main-service:
    build:
      context: ./main_service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - product-catalog-service
      - order-management-service
      - payment-service
      - inventory-service
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge