runtime: python27
api_version: 1
threadsafe: true

handlers:
  - url: /styles
    static_dir: styles

  - url: /assets
    static_dir: assets

  - url: /
    static_files: index.html
    upload: index.html

  - url: /(.*)
    static_files: \1
    upload: (.*)