FROM nginx:latest

# Remove default Nginx static files and add your own
COPY ./index.html /usr/share/nginx/html/index.html
COPY ./dark.css /usr/share/nginx/html
COPY ./script.js /usr/share/nginx/html
